services:
  - type: web
    name: classroom-attendance
    env: node
    buildCommand: |
      cd client
      npm ci
      npm run build
      cd ..
      npm ci
      npx prisma generate --schema=./prisma/schema.prisma
      npx tsc
    startCommand: node dist/server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: neondb
          property: connectionString
      - key: NODE_ENV
        value: production
